# Site settings
title: Snell Lab
email: kathryn.snell@colorado.edu
owner: Kathryn Snell
description: > # this means to ignore newlines until "baseurl:"
  This is the official website of the Snell Lab in the Department of Geosciences
  at the University of Colorado in Boulder
url: "http://snelllab.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
